### ISSUE TITLE
Corrections/edits to AGN Section (in several tasks)

### ISSUE THREAD

**Issue by daranorman** [brantr/ExtragalacticScienceRoadmap#12]
HI @brantr, Changes and additions in **BOLD** ... rest is for context.  Please let me know if you prefer me to make these changes directly.  @daranorman

3.1.1 AGN Selection from LSST Data 
AGN-1. Motivation: LSST multiband photometry may select Active Galactic Nuclei using a variety of different methods. At optical and near infrared wavelengths, the distinctive colors of AGN at particular redshifts enables their photometric selection **(e.g., Richards et al. 2006 ApJS, 166, 470)**. The LSST data will therefore augment methods that rely on X-ray or radio activity, or the identification of emission lines in spectroscopic data. LSST will also open up, in a more practical way, the identification of AGN based on their variability…
Deliverables:  (c) Development of algorithms **that probe how color selection accounts for AGN variability.** 

3.1.2 AGN Host Galaxy Properties from LSST Data 
AGN-2. Motivation: Morphological characterizations from parameterized models, such as multiple-component Sersic (1968) profiles, or non-parametric measures like CAS and Gini-M20 (Abraham et al., 1994; Conselice et al., 2000; Lotz et al., 2004) can help identify **merging** …
3.1.5 AGN Photometric Redshifts from LSST Data 
Activities: Initial efforts include a comprehensive review of the state of the art in AGN host galaxy photo-z determinations and an analysis of AGN vs. non-AGN galaxy photo-z performance. A comparison of model and/or observed AGN host SEDs with a matched set of non-host galaxies at a variety of redshifts will help engineer color selection criteria for identifying AGN hosts, and whether variability can break photo-z degeneracies.  **This task is complementary to work being done in 3.7.5 (Photometric Redshifts) and should be coordinated with those efforts.**
Deliverables: (b) **Analysis** of multiwavelength, morphological, or variability information that might break photo-z degeneracies. 

3.1.6 AGN Merger Signatures from LSST Data 

Activities: Create simulated or identify real images that contain known galaxy mergers, including systems with and without visible AGN. Run the LSST software stack on these images, and engineer metrics that quantify the accurate detection of galaxy mergers with and without AGN.  **Activities for detecting some of these low surface brightness (LSB) features will be similar to activities in task 3.4.1 (Galaxy Evolution) and should be coordinated with those efforts.**

Deliverables: (a) Characterization and optimization of the ability of the LSST Level 2 data to enable the detection of galaxy mergers **that host** AGN. 
(b) **Identification of catalog parameters or merging galaxy images with properties that will prove challenging to identify (semi-) automatically in the LSST dataset.**

**Comment by brantr** [comment]
Awesome, thank you.  I’ll work to make these changes.
-------------------------------------------------------------------
Brant Robertson
Associate Professor
Astronomy and Astrophysics
UC Santa Cruz
brant@ucsc.edu

**Comment by brantr** [comment]
Hi @daranorman , I made these changes with minor edits, thank you!
