### ISSUE TITLE
3.1.3 Deliverable (a) suggested rewording

### ISSUE THREAD

**Issue by hcferguson** [brantr/ExtragalacticScienceRoadmap#14]
"Investigation of the number of BCGs and the mass range of their clusters with redshift that LSST will likely observe."

This one seems a bit out of place, since one imagines (even if it isn’t true) that this sort of estimate has already been made. I would suggest as an alternative “Investigate and quantify the ability of the LSST pipeline to select BCG’s using precursor datasets such as the HSC survey.”

**Comment by brantr** [comment]
Re-wrote as:

Investigation and quantification of the ability of the LSST pipeline to select BCGs using precursor datasets such as the HSC survey.

I've been using nouns rather than verbs for deliverables.
