### ISSUE TITLE
3.2.4 (a) suggested additional text

### ISSUE THREAD

**Issue by hcferguson** [brantr/ExtragalacticScienceRoadmap#15]
Guidance for LSST galaxy pipelines to include all the necessary information for measurements of the correlation function and related statistics to take place once LSST data is available. This requires ancillary products such as masks and maps of completeness as a function of galaxy properties.

**Comment by brantr** [comment]
Rewording to avoid "This <verb>" construction:

Guidance for LSST galaxy pipelines to include all the necessary information for measurements of the correlation function and related statistics to take place once LSST data is available. This deliverable requires the engineering of ancillary products such as masks and maps of completeness as a function of galaxy properties.
