### ISSUE TITLE
Do we need section 2.4?

### ISSUE THREAD

**Issue by hcferguson** [brantr/ExtragalacticScienceRoadmap#17]
Photometric redshifts are more of a tool than a science goal. I wonder if we could simply delete section 2.4, since we discuss photometric redshifts in section 3.7?

**Comment by sschmidt23** [comment]
Even if you view photo-z's as a tool, if you're estimating galaxy properties like M* and SFR and you aren't doing it as a joint fit with redshift, then you're doing it wrong.  Photo-z estimation goes hand in hand with any estimates of physical parameters for photometric surveys like LSST.  I thought this section made that point, but maybe that has to be strengthened slightly?

**Comment by brantr** [comment]
I changed the first paragraph of the section to read "As a purely photometric survey, LSST provides an exquisite data set of two-dimensional images of the sky in six passbands.  
However, the third dimension of cosmic distance to each galaxy must often
come from photometric redshifts (photo-$z$'s). Many quantities that LSST data can
reveal about distant galaxy populations, including intrinsic luminosities, physical
sizes, star formation rates, and stellar masses, will ultimately rely on photo-$z$ 
determinations. The engineering of accurate and precise photo-$z$ methods
therefore represents an important science effort for LSST science collaborations."

The hope is this clarifies the scientific utility of photo-z's.  I'm going to close the issue, but re-open it (soon) if you disagree.
